name: Firebase Functions CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      - name: Check if functions directory exists
        run: |
          if [ -d "functions" ]; then
            cd functions
            npm install
          else
            echo "El directorio 'functions' no existe"
            exit 1
          fi

      - name: Deploy Firebase Functions
        run: firebase deploy --only functions --token ${{ secrets.FIREBASE_TOKEN }}
